### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by dinosw** [Zoltanar/Happy-Search#1]
This is surely an amazing app how have created, but I do however have one small question/request.
Could it be made, so that all data relating to Happy Search, is stored within the folder itself?
The data and such are already stored there, but the user settings aren't.
I would like to have it run completely from OneDrive, it is already very near to being able to do so, except for the usersettings.
I am using 1.4.2, not being able to search the whole of VNDB is not much of issue for me, the program works perfectly for managing userlists/wishlists, as intended.
So far, I have had no issues with 1.4.2, if any occur, I will report them to you :)

Best Regards
Steven

PS.: Thank you for putting in the effort and time, in making this program.

**Comment by Zoltanar** [comment]
Thanks for the feedback, yes I can store all the settings in a file, except the user's password,  which is currently stored in the windows registry (encrypted).  If you want to run the risk of storing your password along with the other user settings, I can implement that too, as an optional cmd argument so that other users aren't affected.

**Comment by dinosw** [comment]
I would really appreciate the settings being stored in such a way. The password storage solutions, isn't necessary.
Thank you for your quick response.

**Comment by Zoltanar** [comment]
I've uploaded a new release (1.4.3) with the changes you requested.

**Comment by dinosw** [comment]
Thank you very much, I'll try it out a bit later, when I am at my computer again.
