### ISSUE TITLE
Language Flags

### ISSUE THREAD

**Issue by dinosw** [Zoltanar/Happy-Search#3]
Hi again, sorry to keep opening issues c'',)
When viewing visual novels in grid view, we can see flag representing the country of origin for each game, [like this](https://goo.gl/LmDnCR).
I was wondering, if it might be possible to have all supported languages shown for each game, like in the [info page](https://goo.gl/y5YO2W) for a game.

Best Regards
Steven Windfeld

**Comment by Zoltanar** [comment]
I don't want the tiles to be covered in flags, which is why I only show the original language(s) in them.

I could perhaps add it as an option but are you aware of the language search? 
You are able to see titles available in a specific language, but then you can easily see in the results the original language of said titles (for e.g. if you are only interested in originally japanese stuff).

**Comment by dinosw** [comment]
My thoughts were more in regards to seeing both english and japanese flags for translated projects. An option could be nice. On VNDB i use [VNDB Extender - Chrome Webshop](https://chrome.google.com/webstore/detail/vndb-extender/bljhbeelihmapgmngdgmindaplllicoc) to quickly get an overview in regards to translation status, the website itself lacks alot of features, but with that extension and a few userscripts, I can at least extend the functionality. Your program really is a fantastic tool for organizing lists further. Might it be possible instead to add an option akin to the above mentioned chrome extension, in regards to viewing translation status?
The language search? in happy search? I know that I can filter results on vndb, but if the option is available in happy search, I must have missed it.
I am simply throwing a few ideas into the air, if you do not want to, or find them bothersome etc... Then you may easily disregard my ideas, I am by no means trying to make demands or anything, as I am grateful that you have already taken the time to create this tool in the first place.
If you were to make an option for additional flags, then perhaps a a full translation could be marked by a fully colored flag, and a partial/incomplete translation could be marked by a flag, where only half is colored (for instance a diagonal line marking the division between a colorized half, and a gray-toned half).

**Comment by Zoltanar** [comment]
Firstly, I welcome any suggestions, don't be shy to ask for features that you might like.

I could indeed make flags appear with slight changes showing translation status, to be exact I think I would do it like this:

There would be 2 parameters, release date and type:
If a release already happened (the release date is before or today) then it has a opaque flag.
If a release hasn't happened yet (the release date is after today) then it has a transparent flag.
If a release is complete, then it is fully colored,
If a release is partial/trial/etc, then it is colored on the top left diagonal half (as you described above)

I will have to test if the transparent flags will be easily distinguishable from the normal flags.
And the limitation of 6 flags (I think) will still be present since there isn't space for any more.
I also want to add a more descriptive section for the flags in VN tabs.

Regarding language search, it's in the dropdown menu next to 'List' at the left, you can select a language there and only titles with at least one release in that language, will be shown.

**Comment by dinosw** [comment]
Thank you, I hadn't seen that language search function, however, when I use that search function, I simply feel like I am missing the regular search function. to the right of the search, there is some unused space, perhaps a second search field could be added?
I really like your way of thinking in regards to the flags idea, in addition, if you did it the way you are saying, you could also add an option for selecting languages to be shown with flags.

**Comment by Zoltanar** [comment]
Issues closed as development in this application has ended, follow https://github.com/Zoltanar/Happy-Reader instead.
